version: '3.8'

services:
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  node1:
    build: .
    ports:
      - "8080:8080"
      - "7946:7946"
    environment:
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    depends_on:
      - minio

  node2:
    build: .
    ports:
      - "8081:8080"
      - "7947:7946"
    environment:
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - SEEDS=node1:7946
    depends_on:
      - node1

  node3:
    build: .
    ports:
      - "8082:8080"
      - "7948:7946"
    environment:
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - SEEDS=node1:7946
    depends_on:
      - node1

volumes:
  minio_data: 