apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sprawl-phase2
  namespace: sprawl
  labels:
    app: sprawl-phase2
spec:
  serviceName: sprawl-phase2
  replicas: 1
  selector:
    matchLabels:
      app: sprawl-phase2
  template:
    metadata:
      labels:
        app: sprawl-phase2
    spec:
      containers:
      - name: sprawl
        image: sprawl:phase2-complete
        imagePullPolicy: Never
        ports:
        - containerPort: 7946
          name: gossip
        - containerPort: 7947
          name: raft
        - containerPort: 8080
          name: http
        env:
        - name: SPRAWL_BIND_ADDR
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SPRAWL_ADVERTISE_ADDR
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SPRAWL_RAFT_PORT
          value: "7947"
        - name: SPRAWL_CLUSTER_SEEDS
          value: "sprawl-phase2-0.sprawl-phase2.sprawl.svc.cluster.local:7946"
        - name: SPRAWL_DATA_DIR
          value: "/data"
        - name: SPRAWL_HTTP_PORT
          value: "8080"
        readinessProbe:
          httpGet:
            path: /metrics
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /status
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 15
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: sprawl-phase2
  namespace: sprawl
spec:
  clusterIP: None
  selector:
    app: sprawl-phase2
  ports:
  - port: 7946
    name: gossip
  - port: 7947
    name: raft
  - port: 8080
    name: http
---
apiVersion: v1
kind: Service
metadata:
  name: sprawl-phase2-lb
  namespace: sprawl
  labels:
    app: sprawl-phase2
spec:
  type: LoadBalancer
  selector:
    app: sprawl-phase2
  ports:
  - port: 8080
    name: http
    targetPort: 8080 